name: Deploy to Production

# on:
#   push:
#     tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: crpi-zcgiub6jx8rljw6m.cn-hangzhou.personal.cr.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: crpi-zcgiub6jx8rljw6m.cn-hangzhou.personal.cr.aliyuncs.com/zhama-ai/homepage
        tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    # Example deployment to a server via SSH
    # Uncomment and configure according to your deployment setup
    # - name: Deploy to server
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.KEY }}
    #     script: |
    #       docker pull ${{ secrets.DOCKER_USERNAME }}/zhama-homepage:latest
    #       docker stop zhama-homepage || true
    #       docker rm zhama-homepage || true
    #       docker run -d --name zhama-homepage -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/zhama-homepage:latest 